### ISSUE TITLE
Tensor shape not matching

### ISSUE THREAD

**Issue by rwill128** [XHUJOY/pysc2-agents#10]
Hi,

I'm getting this error when I try to run the basic pre-trained agent available for download.

The call stack has my python version, my GPU, etc.

I'm using the newest GIT version of pysc2, which I think means my pysc2 and s2clientprotocol version are 1.2 instead of 1.1.

> C:\Users\Rick\Desktop\pysc2-agents>python -m main --map=MoveToBeacon --training=false
W0203 14:01:37.877619  1860 tf_logging.py:118] From C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\clip_ops.py:110: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-02-03 14:01:38.338341: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-02-03 14:01:38.600618: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.64GiB
2018-02-03 14:01:38.600763: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
I0203 14:01:40.828442  1860 tf_logging.py:110] Restoring parameters from ./snapshot/MoveToBeacon/fcn\model.pkl-100001
Traceback (most recent call last):
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [5,5,42,16] rhs shape= [5,5,23,16]
         [[Node: save/Assign_34 = Assign[T=DT_FLOAT, _class=["loc:@sconv1/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sconv1/weights/RMSProp, save/RestoreV2_34)]]

**Comment by jkafrouni** [comment]
@rwill128 did you figure out what was wrong ? running into the exact same problem now... (pysc2 version 1.2 from pip)
